name: Buildroot workflow
on:
  workflow_dispatch:
  push:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          echo "matrix=$(cat matrix.json | tr '\n' ' ' | sed 's/\s//g')" >> $GITHUB_OUTPUT

  build:
    needs: set-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    name: Build image
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      options: --user root
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cp utils/debian.sources /etc/apt/sources.list.d/debian.sources
          apt-get update
          apt-get install -y --no-install-recommends \
              build-essential \
              ca-certificates \
              cpio \
              curl \
              file \
              git \
              python3 \
              python3-pip \
              python3-setuptools \
              python3-wheel \
              rsync \
              unzip \
              wget \
              xz-utils \
              tree \
              procps

          apt-get build-dep -y linux || apt install -f

      - name: Debug 
        run: |
          pwd
          tree .
